name: Booking Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name appointmentscheduleracr

      - run: |
          docker build \
          -t appointmentscheduleracr.azurecr.io/bookingservice:${{ github.sha }} \
          -f AppointmentScheduler.BookingService/Dockerfile .

      - run: |
          docker push appointmentscheduleracr.azurecr.io/bookingservice:${{ github.sha }}

      - run: |
          az containerapp update \
            --name bookingservices \
            --resource-group VisualStudioOnline-FECBB64602464D1F90BA5DC5D1CA72B4 \
            --image appointmentscheduleracr.azurecr.io/bookingservice:${{ github.sha }}
